<?php

/**
 * BaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Stores
 * @property Doctrine_Collection $StoreTag
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getStores()   Returns the current record's "Stores" collection
 * @method Doctrine_Collection getStoreTag() Returns the current record's "StoreTag" collection
 * @method Tag                 setId()       Sets the current record's "id" value
 * @method Tag                 setName()     Sets the current record's "name" value
 * @method Tag                 setStores()   Sets the current record's "Stores" collection
 * @method Tag                 setStoreTag() Sets the current record's "StoreTag" collection
 * 
 * @package    qhawpay
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@qhawpay.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTag extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_tag');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));


        $this->index('u_name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Store as Stores', array(
             'refClass' => 'StoreTag',
             'local' => 'tag_id',
             'foreign' => 'store_id'));

        $this->hasMany('StoreTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
    }
}