<?php

/**
 * BaseOffer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $store_id
 * @property integer $address_id
 * @property integer $customer_id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property string $active
 * @property datetime $expiration_date
 * @property Address $Address
 * @property Customer $Customer
 * @property Store $Store
 * 
 * @method integer  getId()              Returns the current record's "id" value
 * @method integer  getStoreId()         Returns the current record's "store_id" value
 * @method integer  getAddressId()       Returns the current record's "address_id" value
 * @method integer  getCustomerId()      Returns the current record's "customer_id" value
 * @method string   getTitle()           Returns the current record's "title" value
 * @method string   getDescription()     Returns the current record's "description" value
 * @method string   getImage()           Returns the current record's "image" value
 * @method string   getActive()          Returns the current record's "active" value
 * @method datetime getExpirationDate()  Returns the current record's "expiration_date" value
 * @method Address  getAddress()         Returns the current record's "Address" value
 * @method Customer getCustomer()        Returns the current record's "Customer" value
 * @method Store    getStore()           Returns the current record's "Store" value
 * @method Offer    setId()              Sets the current record's "id" value
 * @method Offer    setStoreId()         Sets the current record's "store_id" value
 * @method Offer    setAddressId()       Sets the current record's "address_id" value
 * @method Offer    setCustomerId()      Sets the current record's "customer_id" value
 * @method Offer    setTitle()           Sets the current record's "title" value
 * @method Offer    setDescription()     Sets the current record's "description" value
 * @method Offer    setImage()           Sets the current record's "image" value
 * @method Offer    setActive()          Sets the current record's "active" value
 * @method Offer    setExpirationDate()  Sets the current record's "expiration_date" value
 * @method Offer    setAddress()         Sets the current record's "Address" value
 * @method Offer    setCustomer()        Sets the current record's "Customer" value
 * @method Offer    setStore()           Sets the current record's "Store" value
 * 
 * @package    qhawpay
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@qhawpay.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOffer extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_offer');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('store_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('address_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('customer_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             'notnull' => false,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('expiration_date', 'datetime', null, array(
             'type' => 'datetime',
             ));


        $this->index('i_title', array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Address', array(
             'local' => 'address_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Customer', array(
             'local' => 'customer_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Store', array(
             'local' => 'store_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}