<?php

/**
 * BaseStoreService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $store_id
 * @property integer $service_id
 * @property Store $Store
 * @property Service $Service
 * 
 * @method integer      getStoreId()    Returns the current record's "store_id" value
 * @method integer      getServiceId()  Returns the current record's "service_id" value
 * @method Store        getStore()      Returns the current record's "Store" value
 * @method Service      getService()    Returns the current record's "Service" value
 * @method StoreService setStoreId()    Sets the current record's "store_id" value
 * @method StoreService setServiceId()  Sets the current record's "service_id" value
 * @method StoreService setStore()      Sets the current record's "Store" value
 * @method StoreService setService()    Sets the current record's "Service" value
 * 
 * @package    qhawpay
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@qhawpay.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStoreService extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_store_service');
        $this->hasColumn('store_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));
        $this->hasColumn('service_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Store', array(
             'local' => 'store_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Service', array(
             'local' => 'service_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}