<?php

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $country_id
 * @property string $code
 * @property string $name
 * @property string $description
 * @property string $image
 * @property string $active
 * @property Country $Country
 * @property Doctrine_Collection $Addresses
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getCountryId()   Returns the current record's "country_id" value
 * @method string              getCode()        Returns the current record's "code" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getImage()       Returns the current record's "image" value
 * @method string              getActive()      Returns the current record's "active" value
 * @method Country             getCountry()     Returns the current record's "Country" value
 * @method Doctrine_Collection getAddresses()   Returns the current record's "Addresses" collection
 * @method City                setId()          Sets the current record's "id" value
 * @method City                setCountryId()   Sets the current record's "country_id" value
 * @method City                setCode()        Sets the current record's "code" value
 * @method City                setName()        Sets the current record's "name" value
 * @method City                setDescription() Sets the current record's "description" value
 * @method City                setImage()       Sets the current record's "image" value
 * @method City                setActive()      Sets the current record's "active" value
 * @method City                setCountry()     Sets the current record's "Country" value
 * @method City                setAddresses()   Sets the current record's "Addresses" collection
 * 
 * @package    qhawpay
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@qhawpay.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_city');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('country_id', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             'notnull' => true,
             ));
        $this->hasColumn('code', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 5000, array(
             'type' => 'string',
             'length' => 5000,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('active', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             'fixed' => 1,
             'notnull' => true,
             'default' => 0,
             ));


        $this->index('i_code', array(
             'fields' => 
             array(
              0 => 'code',
             ),
             ));
        $this->index('i_active', array(
             'fields' => 
             array(
              0 => 'active',
             ),
             ));
        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
        $this->option('boolean_columns', array(
             0 => 'active',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Address as Addresses', array(
             'local' => 'id',
             'foreign' => 'city_id'));

        $sluggableext0 = new Doctrine_Template_SluggableExt(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($sluggableext0);
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}