# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
#########################
########## Photo ########
#########################

photo_show:
  url:             /photo/:slug.:sf_format
  param:           { module: Photo, action: show, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { slug: \w+, sf_method: GET }

photo_list:
  url:             /photo/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: Photo, action: list, filter_by: name, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }



############################
########## Category ########
############################

category_show:
  url:             /category/:slug.:sf_format
  param:           { module: Category, action: show, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { slug: \w+, sf_method: GET }

category_list:
  url:             /category/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: Category, action: list, filter_by: name, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }



  
###########################
######### General #########
###########################

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
  
  
