comment:
  url:             /comment.:sf_format
  param:           { module: Photo, action: comment, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { sf_method: POST }

register:
  url:             /register.:sf_format
  param:           { module: Customer, action: register, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { sf_method: POST }

login:
  url:             /login.:sf_format
  param:           { module: Customer, action: login, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { sf_method: POST }

store_service_list:
  url:             /store/service/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: StoreService, action: list, filter_by: service_id, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }



store_category_list:
  url:             /store/category/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: StoreCategory, action: list, filter_by: category_id, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }


#######################
########## Store ######
#######################

store_show:
  url:             /store/:slug.:sf_format
  param:           { module: Store, action: show, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { slug: \w+, sf_method: GET }

store_list:
  url:             /store/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: Store, action: list, filter_by: name, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }



#########################
########## Service ######
#########################

service_show:
  url:             /service/:slug.:sf_format
  param:           { module: Service, action: show, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { slug: \w+, sf_method: GET }

service_list:
  url:             /service/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: Service, action: list, filter_by: name, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }



#########################
########## Photo ########
#########################

photo_show:
  url:             /photo/:slug.:sf_format
  param:           { module: Photo, action: show, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { slug: \w+, sf_method: GET }

photo_list:
  url:             /photo/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: Photo, action: list, filter_by: name, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }



############################
########## Category ########
############################

category_show:
  url:             /category/:slug.:sf_format
  param:           { module: Category, action: show, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { slug: \w+, sf_method: GET }

category_list:
  url:             /category/:filter_by/:filter/:order_by/:order/:max/:page.:sf_format
  param:           { module: Category, action: list, filter_by: name, filter: 0, order_by: created_at, order: d, max: 20, page: 1, sf_format: xml }
  class:           sfRequestRoute
  requirements:    { filter_by: \w+, filter: '[^\/^\s]+', order_by: \w+, order: \w+, max: \d+, page: \d+, sf_method: GET }



  
###########################
######### General #########
###########################

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
  
  
