<?php

/**
 * AddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddressTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Address');
    }
}