<?php

/**
 * ServiceCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServiceCategoryTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServiceCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ServiceCategory');
    }
}