<?php

/**
 * StoreTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoreTagTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoreTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoreTag');
    }
}