<?php

/**
 * StoreCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoreCategoryTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoreCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoreCategory');
    }
}