<?php

/**
 * StoreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoreTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Store');
    }
const
    STATUS_PENDING = 'PE',
    STATUS_ACTIVATED = 'AC',
    STATUS_CANCELED = 'CA';        

  protected static
    $status = array
              (
                self::STATUS_PENDING => 'Pendiente',
                self::STATUS_ACTIVATED => 'Activado',
                self::STATUS_CANCELED => 'Cancelado',
              );
                              
  public function getStatuss()
  {
    return self::$status;
  }
  
  public function updateQueryForList(DoctrineQuery $q, $params)
  {
      if($params['category_id'] <> null)
      {
      $q = DoctrineQuery::create()->select('s.*')
              ->from('StoreCategory sc')
              ->innerJoin('sc.Store s')
              ->innerJoin('sc.Category c')
              ->where('c.id = ?', $params['category_id'])
              ->limit(100);
      }
      
      if($params['service_id'] <> null)
      {
      $q = DoctrineQuery::create()->select('s.*')
              ->from('StoreService sse')
              ->innerJoin('sse.Store s')
              ->innerJoin('sse.Service se')
              ->where('se.id = ?', $params['service_id'])
              ->limit(100);
      }
  }
}