<?php

/**
 * StoreServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StoreServiceTable extends DoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object StoreServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StoreService');
    }
}