##############################
######### Default ############
##############################
panel_index:
  url:             /panel
  param:           { module: Panel, action: index }

login_facebook:
  url:             /login/facebook/*
  param:           { module: Log, action: loginFacebook }

homepage:
  url:             /
  param:           { module: Home, action: index }

default:
  url:             /:module/:action/*