default:
  http_metas:
    content-type: text/html

  metas:
    title:        Qhawpay
    description:  Dentro de poco podrás tener a tu disposición la mas completa información de establecimientos de interés y ofertas inimaginables.
    keywords:     lugares, online, qhawpay,peru, plataforma,gratis,free
    language:     es
    robots:       index, follow

  stylesheets:
    - frontend/reset.css:   { media: screen }
    - frontend/text.css:    { media: screen }
    - frontend/960.css:     { media: screen }
    - frontend/main.css:    { media: screen }
    - frontend/styles.css: { media: screen }    
    - frontend/niceforms-default.css: { media: screen }
    
  javascripts:
    - jquery/jquery-1.4.2.min.js
    - jquery/jquery-ui-1.8.min.js
    - jquery/mousewheel.pack.js
    - jquery/fancybox.pack.js
    - general/general.js
    - frontend/ddaccordion.js
    - frontend/jconfirmation.jquery.js
    - frontend/niceforms.js
    
  has_layout:     true
  layout:         layout