<?php

/**
 * BaseGoogleAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $user_token
 * @property timestamp $last_login
 * 
 * @method string        getUserToken()  Returns the current record's "user_token" value
 * @method timestamp     getLastLogin()  Returns the current record's "last_login" value
 * @method GoogleAccount setUserToken()  Sets the current record's "user_token" value
 * @method GoogleAccount setLastLogin()  Sets the current record's "last_login" value
 * 
 * @package    qhawpay
 * @subpackage model
 * @author     David Joan Tataje Mendoza <dtataje@qhawpay.pe>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGoogleAccount extends DoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('google_account');
        $this->hasColumn('user_token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}