Country:
  tableName:                        t_country
  actAs:
    SluggableExt:                   { fields: [ name ] }
    Timestampable:
  columns:
    id:                             { type: integer  , length: 20 , primary: true    , autoincrement: true                                                 }
    code:                           { type: string   , length: 5                     , notnull: true                                                       }
    name:                           { type: string   , length: 100                   , notnull: true                                                       }
    description:                    { type: string   , length: 5000                                                                                        }
    image:                          { type: string   , length: 255                                                                                         }
    active:                         { type: string   , length: 1  , fixed: true      , notnull: true , default: 0                                          }
  indexes:
    u_code:                         { fields: [ code ]                               , type: unique                                                        }
    u_name:                         { fields: [ name ]                               , type: unique                                                        }
    i_active:                       { fields: [ active ]                                                                                                   }
  relations:
    City:                           { class: City              , local: id                    , foreign: country_id        , type: many                , alias: Cities  }
  options:
    symfony:                           { filter: false, form: false }    

City:
  tableName:                        t_city
  actAs:
    SluggableExt:                   { fields: [ name ] }
    Timestampable:
  columns:
    id:                             { type: integer  , length: 20 , primary: true    , autoincrement: true                                                 }
    country_id:                     { type: integer  , length: 20                    , notnull: true                                                       }
    code:                           { type: string   , length: 5                     , notnull: true                                                       }
    name:                           { type: string   , length: 100                   , notnull: true                                                       }
    description:                    { type: string   , length: 5000                                                                                        }
    image:                          { type: string   , length: 255                                                                                         }
    active:                         { type: string   , length: 1  , fixed: true      , notnull: true , default: 0                                          }
  indexes:
    i_active:                       { fields: [ active ]                                                                                                   }
  relations:
    Country:                        { class: Country           , local: country_id            , foreign: id                , type: one                 , alias: Country           , onDelete: RESTRICT, onUpdate: CASCADE }
    Address:                        { class: Address           , local: id                    , foreign: city_id        , type: many                , alias: Addresses                                                    }
  options:
    symfony:                           { filter: false, form: false }